name: Test
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        otp:
        - "23.3"
        - "24.3"
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - name: Deps
      run: rebar3 get-deps
    - name: Compile
      run: rebar3 compile
    - name: Dialyze
      run: rebar3 dialyzer
    - name: EUnit
      run: rebar3 eunit
    - name: Common Test
      run: rebar3 ct
    - name: Capture Test Logs on Failure
      uses: actions/upload-artifact@v2-preview
      if: failure()
      with:
        name: ct-logs-${{matrix.otp}}
        path: logs/*